services:
  - type: web
    name: document-analyzer
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: PORT
        value: 8080
      - key: FLASK_ENV
        value: production
    scaling:
      minInstances: 1
      maxInstances: 1
